import type { Metadata } from "next";

import "./globals.scss";
import Providers from "@/app/common/contexts/Providers";
import { inter } from "./fonts"

export const metadata: Metadata = {
  title: "Douglas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
