import type { Metadata } from "next";
import { Montserrat, JetBrains_Mono } from "next/font/google";
import "./globals.scss";

const montSerrat = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "500", "700"],
});
export const metadata: Metadata = {
  title: "Douglas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={montSerrat.className}>{children}</body>
    </html>
  );
}
